### ISSUE TITLE
[HELP] Need help to add flag for endorsement delay

### ISSUE THREAD

**Issue by yashbhavsar007** [serokell/tezos-packaging#300]
I need to use flag '--endorsement-delay 2' because my endorser is endorsing sometime before the actual slot. So, I need to add the flag but not sure where to add the flag. 

Kindly help to add the flag.

**Comment by rvem** [comment]
Hi, I'm assuming that you're using the baking service from [our baking tutorial](https://github.com/serokell/tezos-packaging/blob/master/docs/baking.md).

I think the easiest way is to edit `tezos-endorser-010-ptgranad@.service` configuration.

In order to do that run `sudo systemctl edit --full tezos-endorser-010-ptgranad@.service` and update the `ExecStart`
attribute to look the following way:
```
ExecStart=/usr/bin/tezos-endorser-010-ptgranad-start --endorsement-delay 2
```

Restart the baking service after that for changes to take effect:
```
sudo systemctl restart tezos-baking-<network>.service
```

**Comment by yashbhavsar007** [comment]
Thank you @rvem for the support. Yes, I was following the same baking tutorial. Can you also point me to the doc for updating the version?

**Comment by itkach** [comment]
@yashbhavsar007 you may want[ to join baking slack](tezos-kiln.org/joinbakingslack); latest recommendation there is that with Octez 10.2 you should net set endorsement delay and remove `--endorsement-delay` if you set set it up before.

**Comment by itkach** [comment]
> Can you also point me to the doc for updating the version?

**Comment by yashbhavsar007** [comment]
> @yashbhavsar007 you may want[ to join baking slack](https://tezos-kiln.org/joinbakingslack); latest recommendation there is that with Octez 10.2 you should net set endorsement delay and remove `--endorsement-delay` if you set set it up before.

Yeah sure I would like to join the slack. Thank you for sharing link with me.
How do we net set the endorsement delay?
