### ISSUE TITLE
rpi binaries

### ISSUE THREAD

**Issue by chiptus** [serokell/tezos-packaging#64]
First, let me say how I love this project, and how useful it for me.

I'm currently trying to have a tezos-client on one of my RPI (3b+ arch aarch64) and I can't use your binaries as I get `-bash: ./tezos-client: cannot execute binary file: Exec format error`. Is it because of the different architecture?

 Can we add support for this little machines?

Thanks!

**Comment by gromakovsky** [comment]
Yeah, we were discussing it some time ago. It's on our roadmap. Currently it's hard to estimate how hard it might be, but I guess we'll start working on this issue some time in August and then we'll see.

**Comment by chiptus** [comment]
anything I can do to help?

**Comment by gromakovsky** [comment]
@chiptus did you try running binaries from releases or did you try building them yourself (using the `docker/docker-static-build.sh` script)? If it's the former, can you try running `docker/docker-static-build.sh` on your RPI?

**Comment by chiptus** [comment]
I only tried to build from source using opam.

**Comment by chiptus** [comment]
failed: 

```
The command '/bin/sh -c git clone --single-branch --branch v1.0.23 https://github.com/libusb/libusb.git --depth 1' returned a non-zero code: 139
```

**Comment by rvem** [comment]
Which OS are you using on your Raspberry Pi?

**Comment by chiptus** [comment]
respberry os 64bit (beta)

**Comment by rvem** [comment]
Do you remember how you've installed the docker?
Can it be something similar to https://github.com/schollz/find3/issues/1?

**Comment by chiptus** [comment]
I used `curl -sSL https://get.docker.com | sh` as far as I remember

**Comment by rvem** [comment]
I've been playing with qemu and arm alpine docker images in order to build static binaries for `armv7l` or aarch64.
However, I haven't succeeded much in it:(
The issue with `armv7l` caused by the fact that currently ocaml 4.09.1 cannot be easily built on this architecture, thus it's impossible to use opam and its `opam switch create` command in order to build tezos.
The issue with `aarch64` caused by the fact that both `curl` and `wget` fail with SIGSEGV when trying to fetch something from the link that has redirects, thus it's impossible to fetch some sources of the tezos opam dependencies (e.g. astring).
I'll play with `aarch64` a bit more and will try to find the reason of this segfaults.

The other possible direction of the work is to spin up some arm machine on AWS and try to build static tezos binaries there.
When I get some success, I'll send you the binaries for testing.

**Comment by chiptus** [comment]
thx

**Comment by itkach** [comment]
Perhaps it makes sense to focus on building for/on the official [Raspbery Pi OS](https://www.raspberrypi.org/downloads/raspberry-pi-os/) and build .deb packages for it with regular, non-static binaries? Cross-platform builds with https://github.com/docker/buildx also look interesting.

**Comment by rvem** [comment]
> Cross-platform builds with https://github.com/docker/buildx also look interesting
AFAIU, it will do the same thing as I was trying with qemu + arm docker images, so I don't expect to see any differences when using it:(

**Comment by rvem** [comment]
> Perhaps it makes sense to focus on building for/on the official Raspbery Pi OS and build .deb packages for it with regular, non-static binaries?

Yes, that should work. Looks like `dpkg-buildpackage` supports cross-compilation

**Comment by rvem** [comment]
@chiptus, [here are](https://drive.google.com/file/d/1MTP2Mpbst-JMGrvx3Qqqjp5rAjvHLaRX/view?usp=sharing) the static binaries compiled for aarch64, could you please check that they work for you?

**Comment by rvem** [comment]
Well, if these two binaries didn't instantly fail with segfault, this probably means that they're fine:)

Currently, we have [a testing script](https://github.com/serokell/tezos-packaging/blob/master/tests/test_script.py) for tezos binaries that performs some basic actions, it uses nix python-based test engine for x86_64 static binaries built by nix and docker, will extend this testing for aarch64 binaries to be sure that they're fine.

**Comment by rvem** [comment]
Also, take a look at #70 to see how binaries that I've provided to use was built

**Comment by chiptus** [comment]
nice, tyvm
