### ISSUE TITLE
[BUG] Network initialization choices in the wizard are not (always) correct (Windows 10)

### ISSUE THREAD

**Issue by marklnichols** [serokell/tezos-packaging#691]
# Description

On at least one run-through, I saw the incorrect choices:
1. file
2. url.
3. skip

# To Reproduce
Not known how to reproduce this -- it is intermittent

# Expected behavior

The correct 4 choices 
1. download rolling (default)
2. file
3. url
4. skip

# Environment

- OS
Windows 10

**Comment by itkach** [comment]
I think I also may have seen this once. The option came back after immediately restarting the wizard. I was not aware of any loss of network connectivity at the moment.  It is possible that I got very lucky in ran the wizard precisely during a very short connectivity glitch but seems somewhat unlikely. In any case, perhaps silently hiding the option is not the best way to handle this. Network connectivity is essential to the whole setup so not alerting user of the issue here is not helpful. If default snapshot provider (xtz-shots) is down we can try alternative (marigold) (or try them in parallel use one that responds first). Also, first-time users running into this won't even know what they are missing and walk away with an impression that setup wizard does not provide all that much convenience.
