### ISSUE TITLE
Path to v20.1-2 release still points to v20.1-1 directory.

### ISSUE THREAD

**Issue by mturadek-ledger** [serokell/tezos-packaging#813]
# Clarification and motivation

I use automation for building new Docker images:
```
# find the latest version
curl -sX GET "https://api.github.com/repos/serokell/tezos-packaging/releases/latest" | jq --raw-output '.tag_name'
v20.1-2

# download the version
curl --fsSL https://github.com/serokell/tezos-packaging/releases/download/v20.1-2/binaries-octez-v20.1-2.tar.gz -o /app/tezos/binaries-octez-${VERSION}.tar.gz

curl: (22) The requested URL returned error: 404
```

Unfortunately, version 20.1-2 is still downloaded as version 20.1-1, so the pattern needs to be fixed.

# Acceptance criteria

Can you fix the binaries' naming and adequately expose them to the directory (v20.1-2) reflecting the tag (v20.1-2)?

**Comment by DMozhevitin** [comment]
Hi!
Sorry for the inconvenience, this issue was resolved in the [latest release](https://github.com/serokell/tezos-packaging/releases/tag/v20.2-1). The issue was that we didn't bump the release number in one of our scripts.

Is it ok to you to use the latest release with correct binaries names, or you want us to fix them from `v20.1-2`?

**Comment by mturadek-ledger** [comment]
Hi!

Thank you very much for getting back to me so quickly.

There are no other steps needed.

Many thanks!

**Comment by DMozhevitin** [comment]
No problem 😄 , closing the issue then.
