### ISSUE TITLE
Use the official GitHub CLI to create releases

### ISSUE THREAD

**Issue by gromakovsky** [serokell/tezos-packaging#97]
# Clarification and motivation

We are using the `hub` utility to interact with GitHub from CI, but I heard that there is another tool which is officially developed by GitHub and lets you interact with GitHub. Probably it's quite similar to `hub`. I think we should consider switching to it because "being developed by GitHub" sounds like an essential advantage here. 

# Acceptance criteria

1. Evaluate what should be done in order to switch to this tool.
2. If the change is considered good enough, do the switch.

**Comment by rvem** [comment]
So, looks like `gh` provides the same release functionality as `hub` does. The only difference is that. However, [hub repo](https://github.com/github/hub) looks a bit abandoned (there are no updates since august).

However, `gh` version provided in the currently used `nixpkgs` revision is old and doesn't support release related stuff, so in order to use it, we should do #84 first. (Or use dedicated nixpkgs revision just for `gh` but it doesn't sound proper)

**Comment by rvem** [comment]
Okay, our nixpkgs fork is still too old to have at least 1.0.0. version of `gh`

**Comment by gromakovsky** [comment]
Well, maybe we won't need this issue if we move most of this repo into `tezos/tezos` :)
